version: "3.9"

services:
  dashboard:
    build: dashboard
    restart: always
    ports:
      - 5000:5000
  xbnet:
    build: xbnet
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ttyUSB0:/dev/ttyxbnet"
    network_mode: host
    restart: always
  rf:
    build: rf
    privileged: true
    cap_add:
      - CAP_SYS_RAWIO
    devices: # TODO: Make this more generic, only works on my PC right now
      - /dev/hackrf-one-3-6
