version: "3.9"

services:
  xbnet:
    build: xbnet
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ttyUSB0:/dev/ttyxbnet"
    # Steam the rsmb hostname since the rsmb container is using our network namespace
    networks:
      default:
        aliases:
          - rsmb
    ports:
      - 1883:1883 # Forward RSMB for testing
    restart: always
  rsmb:
    # Share a network namespace with xbnet so that we can use it's interface
    network_mode: service:xbnet
    command: rsmb /etc/rsmb.hardware.conf
    depends_on:
      xbnet:
        condition: service_healthy
  rf:
    privileged: true
    cap_add:
      - CAP_SYS_RAWIO
    devices: # TODO: Make this more generic, only works on my PC right now
      - /dev/hackrf-one-3-6
    build: rf
